# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: seeeduino_xiao_rp2040
    shield: le_colibri
  - board: seeeduino_xiao_rp2040
    shield: le_oeuf
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: le_oeuf
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: solanum_left
  - board: nice_nano_v2
    shield: solanum_right
  - board: nice_nano_v2
    shield: egg58bt_left
  - board: nice_nano_v2
    shield: egg58bt_right
